server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=db_query;encrypt=false;trustServerCertificate=true
    username: sa
    password: zz
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

llm:
  api-key: "9ed52aaa3e6d4b50abcd95f9681e7501.CoeTwif44GJaGin0"
  base-url: "https://open.bigmodel.cn/api/anthropic"
  model: glm-4-flash

logging:
  level:
    root: DEBUG
    com.projectalpha: DEBUG